apiVersion: apps/v1
kind: Deployment
metadata:
  name: beauty-deployment
  labels:
    app: beauty
spec:
  replicas: 1
  selector:
    matchLabels:
      app: beauty
  template:
    metadata:
      labels:
        app: beauty
    spec:
      containers:
      - name: beauty
        image: 545365949126.dkr.ecr.us-east-1.amazonaws.com/shopping-site-beauty:95f177b6a2c6b93bb1011e90103fdb0fc1d28f54
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: beauty-service
  labels:
    app: beauty
spec:
  type: ClusterIP
  selector:
    app: beauty
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
