apiVersion: apps/v1
kind: Deployment
metadata:
  name: auto-deployment
  labels:
    app: auto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auto
  template:
    metadata:
      labels:
        app: auto
    spec:
      containers:
      - name: auto
        image: 545365949126.dkr.ecr.us-east-1.amazonaws.com/shopping-site-auto:88d8e461cd973f7f1f11356c1906d6e50c0179fa
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: auto-service
  labels:
    app: auto
spec:
  type: ClusterIP
  selector:
    app: auto
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
